apiVersion: networking.istio.io/v1beta1
kind: ProxyConfig
metadata:
  name: default
  namespace: istio-system
meshConfig:
  defaultConfig:
    proxyStatsMatcher:
      inclusionSuffixes:
       - http
